type: intervention_noise_vae
dim_x: ${data.dim_x}
dim_z: ${data.dim_z}
overwrite_latents: false

averaging_strategy: stochastic

scm:
  type: residual_lipschitz_monotonic
  homoskedastic: false
  adjacency_matrix: none
  manifold_thickness: 0.01
  hidden_units: 100
  hidden_layers: 2
  min_std: 0.2
  # monotonic_constraints: none
  # monotonic_constraints: all
  monotonic_constraints: context_non_mask
  n_groups: 2
  weight_constraint_kind: default
  lipschitz_const: 0.95
  # lipschitz_const: 0.9
  # lipschitz_const: 0.95
  # lipschitz_const: 5.0
  # concat_masks_to_parents: false

encoder:
  type: mlp
  flip: false
  hidden_units: 64
  hidden_layers: 5
  std: 0.01
  min_std: 0.0001
  fix_std: false

decoder:
  hidden_units: 64
  hidden_layers: 5
  std: 1.0
  min_std: 0.001
  fix_std: true

intervention_encoder:
  type: learnable_heuristic
